
<!-- E-Zone business -->

<div class = "page-dark-gray">

<div class = "wrap-columns">

<div class = "columns-35">

## E-Zone business

Purchases from Portland zip codes

</div>
<div class = "columns-65">

```{r text_q26, fig.height=6}
# clean data
df_ezone_spent <- df_pmp_data |>
  select(year, spend_locally_portland_ezone) |>
  mutate(
    amount = format(
      spend_locally_portland_ezone,
      big.mark = ",",
      scientific = FALSE
    ),
    amount = case_when(grepl("NA", amount) ~ "Did not track", TRUE ~ paste0("$ ", amount)),
    text_colour = case_when(
      amount == "Did not track" ~ pmp_palette$`Light blue`,
      TRUE ~ pmp_palette$Gray
    ),
    text_size = case_when(year == max(year) ~ 8 + (year - 2018), TRUE ~ 6 + (year - 2018))
  )

# graph
ggplot(df_ezone_spent, aes(x = 0, y = year)) +
  ggtext::geom_textbox(
    aes(
      label = amount,
      color = text_colour,
      alpha = year
    ),
    family = "Gilroy ExtraBold",
    minwidth = unit(4, "in"),
    maxwidth = unit(4, "in"),
    box.size = 1.5,
    size = df_ezone_spent$text_size,
    box.colour = NA,
    fill = NA,
    box.r = unit(0, "pt"),
    hjust = 0,
    halign = 0,
    vjust = 0.5,
    valign = 0.5
  ) +
  ggtext::geom_textbox(
    aes(label = year, alpha = year),
    color = pmp_palette$Teal,
    family = "Gilroy ExtraBold",
    minwidth = unit(2, "in"),
    maxwidth = unit(2, "in"),
    box.size = 1.5,
    box.colour = NA,
    size = df_ezone_spent$text_size,
    fill = NA,
    hjust = 1.05,
    halign = 1,
    vjust = 0.5,
    valign = 0.5
  ) +
  scale_alpha(range = c(0.6, 1)) +
  scale_colour_identity() +
  theme_void() +
  scale_y_continuous(expand = expansion(mult = 0.5)) +
  scale_x_continuous(expand = expansion(mult = c(0.075, 0.2))) +
  theme(
    panel.background = element_rect(fill = pmp_palette$`Dark teal`, colour = pmp_palette$`Dark teal`),
    legend.position = "none"
  )
```

</div>
</div>

</div>

<!-- E-Zone business -->

<div class = "page-dark-gray">

<div class = "wrap-columns">

<div class = "columns-35">

## E-Zone business

In addition to what you’ve shared about already, what additional steps did your business take to fulfill your Enterprise Zone commitments?

</div>
<div class = "columns-65">

```{r menu_q28a}
menu_across_years(
  data = df_pmp_data,
  questions = df_questions_label,
  question_block = "q28a",
  point_color = pmp_palette$`Dark gray`
)
```
</div>
</div>

</div>

<!-- E-Zone business -->

<div class = "page-inverse-dark-gray">

<!-- Text colour is a blend of the Dark gray and Light gray for readability -->
<span style="color:#8A9A97">
E-Zone, continued
</span>

<div class = "dummy-column-else">

```{r menu_q28b, fig.width = 10.463, fig.height = 9.13}
menu_across_years(
  data = df_pmp_data,
  questions = df_questions_label,
  question_block = "q28b",
  point_color = pmp_palette$`Dark gray`,
  text_size_theme = 16
)

# else text
else_text_q28b <- df_pmp_data |>
  filter(year == params$report_year) |>
  pull(steps_other_ezone) 
```

<span class="something-else"> `r knitr::asis_output(else_text_q28b)` </span>

</div>

</div>
