name: Deploy Website

on:
  workflow_run:
    workflows: [Update data]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    container: rocker/verse:4.4.2
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'deploy'
          
      - name: Install grkmisc
        run: Rscript -e 'remotes::install_github("gerkelab/grkmisc")'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::writexl
            any::here
            any::glue
            any::gt
            any::ggbeeswarm
            any::htmltools
            any::scales
            any::ggiraph
            
      - name: Render and Publish to Netlify
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          path: website/
          