on:
  push:
    branches: main

name: Update data

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: rocker/verse:4.3.0
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Install limer
        run: Rscript -e 'remotes::install_github("cloudyr/limer")'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::janitor 

      - name: Pull data from LimeSurvey
        run: Rscript -e 'source("R/cleaning_scripts/import_data_from_survey_2024.R")'
        env:
          LIMESURVEY_USER: ${{ secrets.LIMESURVEY_USER }}
          LIMESURVEY_PASSWORD: ${{ secrets.LIMESURVEY_PASSWORD }}
          
      - name: Push to branch
        # no need to authenticate since we are in the repo
        run: |
          git config --global user.name "Robot"
          git config --global user.email "tvroylandt@gmail.com"
          git config --global --add safe.directory /__w/portland-means-progress/portland-means-progress
          git checkout -b deploy
          git add .
          git commit -m "Deploy $GITHUB_SHA"
          git push  --set-upstream origin deploy --force

        

